name: wtf_gym_assignment
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.2
  permission_handler: ^11.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  cached_network_image: ^3.2.3
  geolocator: ^10.0.1
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
